### ISSUE TITLE
Urls do provedor de homologação do ginfes retornando 405 (not allowed) 

### ISSUE THREAD

**Issue by cesardddp** [TadaSoftware/PyNFe#177]

**Comment by AlexandreBellas** [comment]
Boa tarde, pessoal.
Este erro está acontecendo novamente para o provedor ginfes. Testei aqui e obtive o erro:
```
Traceback (most recent call last):
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/transport/http.py", line 82, in send
    fp = self.u2open(u2request)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Method Not Allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/transport/http.py", line 94, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Method Not Allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "baixa-nfse/teste.py", line 42, in <module>
    resposta = con.consultar(nfse)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/pynfe/processamento/comunicacao.py", line 569, in consultar
    return self._post_https(url, xml, 'consulta')
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/pynfe/processamento/comunicacao.py", line 742, in _post_https
    raise e
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/pynfe/processamento/comunicacao.py", line 724, in _post_https
    return cliente.service.ConsultarNfseV3(cabecalho, xml)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/home/forfs/.conda/envs/baixanfse/lib/python3.7/site-packages/suds/client.py", line 677, in process_reply
    raise Exception((status, description))
Exception: (405, 'Method Not Allowed')
```

Utilizo o python 3.7. Output das bibliotecas que possuo:
```
python -c 'import OpenSSL; print(OpenSSL.__version__)'          
22.0.0
               
python -c 'import cryptography; print(cryptography.__version__)'
38.0.1

python -c 'import requests; print(requests.__version__)'
2.28.1
```
