### ISSUE TITLE
Sefaz MT Max retries exceeded

### ISSUE THREAD

**Issue by misaelbg** [TadaSoftware/PyNFe#244]
Estou tendo um erro na consulta NFE:

`HTTPSConnectionPool(host='nfe.sefaz.mt.gov.br', port=443): Max retries exceeded with url: /nfews/v2/services/NfeConsulta4?wsdl`

Alguém sabe oq pode ser?

**Comment by leogregianin** [comment]
@misaelbg pode colocar o exemplo de como está fazendo a requisição?

**Comment by misaelbg** [comment]
Segue o erro completo:

`Traceback (most recent call last):
  File "script.py", line 10, in <module>
    envio = con.consulta_nota('nfe', chave_acesso)  # nfe ou nfce
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/pynfe/processamento/comunicacao.py", line 167, in consulta_nota
    return self._post(url, xml)
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/pynfe/processamento/comunicacao.py", line 515, in _post
    raise e
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/pynfe/processamento/comunicacao.py", line 511, in _post
    result = requests.post(url, xml, headers=self._post_header(), cert=chave_cert, verify=False)
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/dopa/Documents/Projects/planos/consulta-nfe/.env/lib/python3.8/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='nfe.sefaz.mt.gov.br', port=443): Max retries exceeded with url: /nfews/v2/services/NfeConsulta4?wsdl (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))`

**Comment by leogregianin** [comment]
Como fez a requisição?
`SSL error` pode ser algo no seu certificado digital. O certificado utilizado está válido?

**Comment by misaelbg** [comment]
Boaa vdd, parece que era o certificado msm!! vlwww
