### ISSUE TITLE
Erro comunicação

### ISSUE THREAD

**Issue by robertowiest** [TadaSoftware/PyNFe#53]
Olá estou com o seguinte erro ao tentar fazer um teste de comunicação

> Traceback (most recent call last):
  File "teste.py", line 11, in <module>
    xml = con.status_servico('nfce')     # nfe ou nfce
  File "/usr/local/lib/python3.5/dist-packages/pynfe/processamento/comunicacao.py", line 262, in status_servico
    return self._post(url, xml)
  File "/usr/local/lib/python3.5/dist-packages/pynfe/processamento/comunicacao.py", line 432, in _post
    raise e
  File "/usr/local/lib/python3.5/dist-packages/pynfe/processamento/comunicacao.py", line 428, in _post
    result = requests.post(url, xml, headers=self._post_header(), cert=chave_cert, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by juniortada** [comment]
Bom dia Roberto!
Qual a UF? 

Ps: precisa utilizar python 3.6 ou superior.

**Comment by juniortada** [comment]
Roberto, acho que você é a primeira pessoa a reportar uso no DF.
Adicionei DF na lista das UF's que utilizam SVRS.
Por favor, atualize sua versão o PyNFe e teste novamente.
Obrigado.

**Comment by juniortada** [comment]
https://github.com/TadaSoftware/PyNFe/commit/94d989ac6c615b572b10100e9173406c78b2f5c7
https://github.com/TadaSoftware/PyNFe/commit/aad0dcd9b8692ddee3731b09a8b2eedfb8f1a9fe

**Comment by robertowiest** [comment]
Olá, fui tentar consultar o status do serviço e está Ok. Porém ao tentar consultar o cadastro ocorreu o seguinte erro

> Traceback (most recent call last):
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd067480710>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robertow/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/robertow/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nfe-homologacao.https', port=443): Max retries exceeded with url: //cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd067480710>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "consulta_cadastro.py", line 9, in <module>
    xml = con.consulta_cadastro('nfe','30695987000177')     # modelo = nfe ou nfce, cnpj(somente números)
  File "/home/robertow/.local/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 220, in consulta_cadastro
    return self._post(url, xml)
  File "/home/robertow/.local/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 431, in _post
    raise e
  File "/home/robertow/.local/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 427, in _post
    result = requests.post(url, xml, headers=self._post_header(), cert=chave_cert, verify=False)
  File "/home/robertow/.local/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/robertow/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/robertow/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/robertow/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/robertow/.local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nfe-homologacao.https', port=443): Max retries exceeded with url: //cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd067480710>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by juniortada** [comment]
DF não possui consulta cadastro NF-e em SVRS.
http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=

**Comment by robertowiest** [comment]
> Traceback (most recent call last):
  File "consulta_cadastro.py", line 9, in <module>
    xml = con.consulta_cadastro('nfce','30695987000177')     # modelo = nfe ou nfce, cnpj(somente números)
  File "/home/robertow/.local/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 208, in consulta_cadastro
    url = self._get_url(modelo=modelo, consulta='CADASTRO')
  File "/home/robertow/.local/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 368, in _get_url
    self.url = NFCE['SVRS'][ambiente] + NFCE['SVRS'][consulta]
KeyError: 'CADASTRO'

**Comment by juniortada** [comment]
NFC-e também não.
http://dec.fazenda.df.gov.br/NFCE/

**Comment by robertowiest** [comment]
Certo. Então estou tentando imprimir uma NF, porém ao tentar validar meu xml no site que voçê me passou esta retornando esse erro 

> Schema XML: The 'http://www.portalfiscal.inf.br/nfe:qrCode' element is invalid - The value '' is invalid according to its datatype 'String' - The Pattern constraint failed.
Caminho: NFe[1]/infNFeSupl/qrCode/

**Comment by juniortada** [comment]
Roberto você está querendo emitir uma NFC-e correto?
Está faltando ou o conteúdo do qrCode está inválido.
Verifique se está fazendo corretamente ou se o seu CSC e TOKEN está correto.

# gera e adiciona o qrcode no xml NT2015/003
xml_com_qrcode = SerializacaoQrcode().gerar_qrcode(token, csc, xml)

https://github.com/TadaSoftware/PyNFe/wiki/Emiss%C3%A3o-de-NFCe
